const image=document.createElement("img");
image.src="";
image.width=150;
image.height=150;
const h4=document.createElemen("h4");
h4.innerText="pricr: 450";
const child=document.createElement("div");
child.className="card";
child.appendChild(image);
child.appendChild(h4);
const parent=document.getElementsByTagName(body);
parent.appendChild(child);
